#
# $RCSfile: Makefile,v $
# $Revision: 1.1 $
# $Date: 1999/11/04 18:06:26 $
# $Locker:  $
#  author: Tucker Balch
#

THISDIR = Domains/Walls
SUBDIRS = 
JAVAFILES := $(shell echo *.java)

include ../../Makefile.src
